[versions]

compose = "1.6.2"
compose-lazyLayouts = "0.2.4"
compose-stylesheet = "0.0.3"
exposed = "0.49.0"
jvmTarget = "17"
koalaplot = "0.5.4"
kotlin = "2.3.10"
kotlinx-collections-immutable = "0.3.7"
kotlinx-coroutines = "1.8.0"
kotlinx-serializationJson = "1.6.3"
multiplatform-settings = "1.1.1"
slf4j = "2.0.13"
sqlite-jdbc = "3.45.3.0"

[libraries]

compose-lazyLayouts = { module = "dev.opensavvy.compose.lazy:lazy-layouts", version.ref = "compose-lazyLayouts" }
compose-stylesheet = { module = "com.moriatsushi.compose.stylesheet:compose-stylesheet", version.ref = "compose-stylesheet" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
koalaplot-core = { module = "io.github.koalaplot:koalaplot-core", version.ref = "koalaplot" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serializationJson" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }
multiplatform-settings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatform-settings" }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }
test-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin" }
test-annotations = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }
test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
